### ISSUE TITLE
Can anyone please guide on how to Install Exercism in our local machine ?

### ISSUE THREAD

**Issue by DheerajV25** [exercism/cli#1017]

**Comment by kotp** [comment]
Not enough information.  What kind of machine?  Please show what you have tried, what has happened when you tried it.

You might also have some luck with support at [the exercism gitter support channel][1], where the help might be more "real time" once someone picks up on it.

If you do choose to ask there, please do prepare a description of what you have read, what you have tried, what operating system you are using, so that as soon as someone sees the question, they may have enough information to really dig in and get started.

[1]: https://gitter.im/exercism/support

**Comment by kotp** [comment]
I can not close this, but it should be (It also provided a note that an actionable issue should have been opened in exercism/exercism which seems to have been ignored. Currently this really is not actionable.

But I can not move nor close this issue.

**Comment by NobbZ** [comment]
Hi @DheerajV25!

I'm sorry you are having trouble installing `exercism` on your PC.

Though as @kotp already says, with the current amount of information there is not much we can do to help you.

I will therefore close this issue.

If the problem persists, please reopen an issue at https://github.com/exercism/exercism/issues and please tell us more about your system:

* What is your operating system
* Have you worked through the official guides in https://exercism.org/cli-walkthrough?
* Which steps did you take so far
* What was their output?
* What did you expect?
