### ISSUE TITLE
No such file or directory with Download cmd.

### ISSUE THREAD

**Issue by dkinzer** [exercism/cli#165]
When I try:

```
exercism download 962b37f2118e4d8b84f1d068ea38354a
```

I see:
```
2015/03/09 14:54:50 open /home/dkinzer/exercism/solutions/dkinzer/Haskell/accumulate/962b37f2118e4d8b84f1d068ea38354a//haskell/accumulate/accumulate.hs: no such file or directory
```

I can see that the file was downloaded properly, so the issue is more cosmetic.

Also, I don't understand how the file is being auto-opened.  The Download command seems to only download and specify where to find the downloaded file.

Debug Info:

```
**** Debug Information ****                    
Exercism CLI Version: 2.0.0                    
OS/Architecture: linux/amd64                   
Home Dir: /home/dkinzer                        
Config file: /home/dkinzer/.exercism.json      
API: http://exercism.io [connected]            
XAPI: http://x.exercism.io [connected]         
Exercises Directory: /home/dkinzer/exercism    
```

**Comment by dkinzer** [comment]
**Correction:**

the file is not all the files are being downloaded.  Specifically, only the test files are being downloaded.  The open command is trying to open the submission file which indeed does not exist.

**Comment by Tonkpils** [comment]
This actually may have to do with the conversation on #152. The issue seems to be with the way the CLI is receiving the file paths. Notice how an extra `/haskell/accumulate/` is appended to it. 

> the file is not all the files are being downloaded. Specifically, only the test files are being downloaded. The open command is trying to open the submission file which indeed does not exist.

I was about to ask if all of the files were downloaded. This is the same issue mentioned above. The `open` portion of the error message is actually the CLI attempting to open the file at that path to write its contents and it fails at doing so. Will post a fix for this while we get the underlying issue fixed.

**Comment by dkinzer** [comment]
Great.  I'll close this as #152 should take care of it.

**Comment by Tonkpils** [comment]
I'd ideally like to leave this open as it can be fixed apart from and this bug hinders the `download` feature.

**Comment by dkinzer** [comment]
Got it.
