### ISSUE TITLE
Write a copy/paste-able release text

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#218]
Last week an interesting thing came up. Newer programmers who are trying to get started with exercism often end up on the cli releases page here on GitHub and they don't quite realize that they're not on exercism, they don't really know why they're downloading or why, and they have no idea where to go next. They're very, very confused.

We should have a markdown text that explains

* What the CLI is
* What dependencies you need (none)
* Which download you should choose (and how to figure out your architecture, if you don't know it)
* What you're going to have to do after downloading it
* [Updates in this release]

Then we can copy/paste that text into the release notes when we cut a new release.

**Comment by Tonkpils** [comment]
> Newer programmers who are trying to get started with exercism often end up on the cli releases page here on GitHub and they don't quite realize that they're not on exercism

Do we know the reason why they end up in the releases page? There was an issue where someone pointed out that their attempt at installing the CLI was because all other options failed and they ended up at the releases page. 

I think any reference to the releases page on the help sections of the website should probably be removed as it should only be used as last option and with some knowledge of where to put this.

I do however agree that having some explanation in the release section would help people when they've exhausted all other installation options.

**Comment by kytrinyx** [comment]
Right now the onboarding process is a mess. We're going to tackle it, but it's going to be a hundred small changes. This would just be one thing that helps orient people if they end up on the releases page.

**Comment by Tonkpils** [comment]
Yeah, I definitely agree. We'll fix that in the mean time here but if there's anything I can do to help out in the front-end of things let me know :smile:

**Comment by kytrinyx** [comment]
Excellent, I expect to be focusing on the onboarding process over the next few weeks, so I'll know more in a bit.
