### ISSUE TITLE
adjust behavior of exercism fetch to avoid noise on the file system

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#226]
Suggestion from @frenata in #2573

------

What if exercism fetch only pulled in exercises for language folders that already exist? This would require that to get started with a new language you'd have to first manually specify it exercism fetch go , but not afterwards.

That way you only get exactly the language exercises that you want. A message to that effect when issuing the command with an empty exercism folder, and I'd guess that the workflow would be a little smoother, avoiding the issue of forgetting to specify a language and ending up with a bunch of subfolders for languages the user isn't interested in.

**Comment by frenata** [comment]
I'm poking around in the codebase to see if I can solve/implement this myself, rather than just ask someone else to. Heh. In the meantime, I ran into an entirely different issue when running the tests...

**Comment by kytrinyx** [comment]
Fun! Ask if you have any questions, we're always happy to help point people in the right direction. And sometimes if the stuff that comes up is too embarrassing, it's a good opportunity to refactor.

**Comment by devonestes** [comment]
:+1: on this feature - I'd also be happy to dive in and see if there are ways I can help, too!

**Comment by Tonkpils** [comment]
I like this idea. This should be fairly simple to implement and I'd be more than happy to pair or help out with whoever wants to tackle this.

**Comment by lcowell** [comment]
I'd be up for pairing. I'd have a couple hours saturday or sunday morning/early afternoon.

**Comment by kytrinyx** [comment]
Any updates on this one? If things have gotten too hectic, feel free to "unclaim" it (just add a comment saying you're too busy or whatever) and then someone else might grab it.

**Comment by devonestes** [comment]
If nobody minds then I think I'll start work on this week. Don't want to steal anyone's thunder, but I'd really love to see this feature added!

**Comment by lcowell** [comment]
:+1: Go for it!

**Comment by frenata** [comment]
I've been busy traveling and visiting family, or I'd have taken a serious shot at this feature--I've not had really much time for exercism at all! I'll try to keep an eye on your work though, devonestes, and if I can carve out the time may do the work myself as well, if only for my own edification.

**Comment by devonestes** [comment]
Ok, after starting some exploration of this, I think there are three ways to solve the problem.

1) Get a list of all the folders that exist in the user's exercises directory and make API calls to the existing endpoint for each of those folders. This is basically the equivalent of looping over the folders on the user's computer and executing `exercism fetch TRACK` for each of those folders.

2) Modify the existing API endpoint for `exercism fetch` so that it can accept multiple tracks as parameters and return the appropriate exercises for only those tracks (rather than either a single track or all tracks, which is the current behavior).

3) Allow the API to return all the tracks, but when iterating over those tracks and saving to disk we skip those tracks with folders which are currently not in the user's exercises folder.

Anyway, I'm leaning towards option 3 at the moment. Option 2 requires a good amount of work that I'm not sure is necessary, and while option 1 is the easiest to implement it's needlessly inefficient on both the server and client side.

I'm going to start working on implementing option 3 and am hoping to get a good chunk of it ready for review tomorrow, but in the meantime any feedback you might have on my thinking would be much appreciated!

**Comment by kytrinyx** [comment]
I like 3 as well.

Option 4 would be to change the API to only return data for tracks where you've submitted at least one problem, but then we run into a thing where if you decide to stop working on a track you can't just delete or move the directory, it would always keep pulling the exercises down.

So... I think 3 is the right approach.

**Comment by Tonkpils** [comment]
I like approach 3 as well. It gives us more flexibility without touching the API

**Comment by kytrinyx** [comment]
Let's start with 3 and add a ticket to the API for 2, which gives us (a) a quick win, and (b) a long term improvement that we can work towards.

**Comment by devonestes** [comment]
@kytrinyx I think this can be closed now that #258 is merged, right?

**Comment by kytrinyx** [comment]
Yepp, thanks!

If you remember to, would you mind adding the `Fixes #NNN` directive in the commit message for the pull request? I tend to forget to check back through open issues.
