### ISSUE TITLE
hello-world exercise not downloaded if already started on track before it was added

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cli#361]
I one has submitted solutions to a track before its `hello-world` exercise was added, the `exercism fetch` command will never fetch the `hello-world` again. This leaves people wondering why Exercism doesn't list the track as completed, when the CLI doesn't fetch any new exercises.

**Comment by kytrinyx** [comment]
I think that it's the correct behavior to _not_ download hello world.

However, I think that we should ignore hello world in the completion stats so that a track can always be considered completed whether or not you did the hello world exercise.

I've opened this issue: https://github.com/exercism/exercism.io/issues/3278
