### ISSUE TITLE
On download, optionally overwrite existing files

### ISSUE THREAD

**Issue by behrtam** [exercism/cli#362]
> Hah, we're doing the rna_transcription test right now and confused b/c one of the people downloaded the ex. last week and only got five tests instead of eight. ([source](https://twitter.com/lpnotes/status/802582657678778368))

I didn't find a cli command to check if a test file for an already downloaded exercise has been changed/updated and an easy way to update that test file other than to delete the exercise directory and fetch it again. Did I just not find it or is this not available?

**Comment by NobbZ** [comment]
It isn't available.

Tammo Behrends <notifications@github.com> schrieb am So., 27. Nov. 2016
11:40:

**Comment by kytrinyx** [comment]
It's not available, but it might be worth implementing a `--force` flag which would overwrite any old test / solution files.

**Comment by behrtam** [comment]
Now that we have more canonical data tests, the new schema with version more and more tracks will move to generated test file. This will lead to more updates of the test suites, which makes it even more important for users to get or at least check for updates to already downloaded exercises.

**Comment by petertseng** [comment]
Even if we can't figure out an answer to whether a file should be overwritten automatically (throwing an idea out there: always overwrite test files, use TestPattern in track config to see whether it's a test file), it is true that showing a diff is "easy" and this allows a student to see whether there is an update.

```diff
diff --git a/user/item.go b/user/item.go
index 2c72d1e..ed8325c 100644
--- a/user/item.go
+++ b/user/item.go
@@ -4,6 +4,7 @@ import (
 	"fmt"
 	"io/ioutil"
 	"os"
+	"os/exec"
 	"path/filepath"
 	"runtime"
 	"strings"
@@ -77,6 +78,13 @@ func (it *Item) Save() error {
 			if err := ioutil.WriteFile(file, []byte(text), 0644); err != nil {
 				return err
 			}
+		} else {
+			cmd := exec.Command("diff", file, "/dev/stdin", "--report-identical-files", "--unified")
+			cmd.Stdin = strings.NewReader(text)
+			// Ignore error since diff returns non-zero if there is a diff.
+			// TODO: check exit status 1 vs 2.
+			out, _ := cmd.CombinedOutput()
+			fmt.Println(string(out))
 		}
 	}
 	return nil
```

I'm sorry, I cannot offer this as a pull request because it is not guaranteed that everyone has `diff` installed. Obviously I can only know whether I have it installed, therefore I run this locally of course. But maybe it will inspire others to have a better idea to do the same. Thanks.

**Comment by americanhanko** [comment]
It isn't pretty, but a quick function in your bash profile allows it to be done from your track directory if the file is the same as the exercise.

`fetch-tests(){
    mv $2/ /tmp/ &&
    exercism fetch $1 $2 &&
    rm $2/$2.py || echo "Could not remove $2.py"
    exercism restore
}`

**Comment by behrtam** [comment]
Until we have a fancy way that automatically handles the the updates to test files, I think we should make the manual way a little bit easier by adding the `--force` flag suggested by @kytrinyx.

Maybe we could also add information about possible updates to the `list` command.

```
$ exercise list python
hello-world
leap  *N
isogram
pangram  *N
rna-transcription
hamming
word-count
gigasecond
[...]

In order to fetch a specific assignment, call the fetch command with a specific assignment.
Note: To fetch the new version (*N) of the test file you need to use the --force option.

exercism fetch python hello-world [--force]
```

**Comment by americanhanko** [comment]
@behrtam @kytrinyx
Tammo, as you stated in https://github.com/exercism/xpython/pull/461
>But with all the changes to the test files, we have to make it easier for people to discover new tests and update the test files

Are changes and updates to test files a desired feature of Exercism or is the goal to eventually have a final version of the test that is no longer able to be updated or changed? Since the problems are user created, the tests are naturally subject to flaws. Additionally, when a user archives a solution, one is effectively saying they've finished the problem. However, unbeknownst to them, it might not be the "right" solution for the most up-to-date test file. To me, new versions of tests mean that: 

* new tests were added to reinforce the described job of the program, edge cases in particular
* inappropriate tests were removed

Ideally, I suppose there would be a review process of problem and, once submitted, the test file becomes solidified and unchangeable. That way, there could be a feature on the site itself that tells you which problems are passing which tests and comparing to other users wouldn't be unfair. This goes hand-in-hand with the fact that you can't see which tests another user's solution is passing (if any), which would be good especially for users who are more inexperienced *and* for seeing progress for each iteration.

Obviously, in TDD, a programmer's code is written based on the tests which are already written, and in many cases, tests do have to get updated, so perhaps the solution is to implement a better "update tests" feature, depending on what the vision is.

**Comment by kytrinyx** [comment]
You all might enjoy this discussion: https://github.com/exercism/discussions/issues/129

**Comment by Insti** [comment]
> check if a test file for an already downloaded exercise has been changed/updated and an easy way to update that test file other than to delete the exercise directory and fetch it again

I wanted to do this today, the command I tried was `exercism fetch --update` (it didn't work obviously.)

**Comment by kytrinyx** [comment]
I like `--update`. A good one to keep in mind.

**Comment by Insti** [comment]
This is still relevant.

**Comment by kytrinyx** [comment]
I'm going to close this in favor of #411  which defines the new download command for nextercism. I plan on implementing #411 over the next few days, as we hope to get the prototype in front of maintainers and contributors in the next week or so.
