### ISSUE TITLE
.exercism.exe.old left behind post `exercism upgrade`

### ISSUE THREAD

**Issue by rpottsoh** [exercism/cli#402]
Relates to #385.  

I have noticed the file `.exercism.exe.old` left behind after `exercism upgrade` has completed.  I am using the CLI in Windows so being able to upgrade is a new thing...  Is leaving a copy of the previous version behind an anticipated thing?

**Comment by Tonkpils** [comment]
Yes, unfortunately windows does not allow you to delete the old executable while it's being used so the upgrader resorts to moving it to this old file while allowing placing the new executable for use. Unless you're running into a specific issue with the upgraded binary then this is the expected behavior! I hope that clears up any confusion!

**Comment by rpottsoh** [comment]
@Tonkpils I have no issue with the expected behavior.  I just wanted to make sure you were aware since upgrading for the Windows CLI is a "new" thing.  I wonder if it is worthwhile to document this behavior.

Thanks for getting back to me.

**Comment by Tonkpils** [comment]
> I wonder if it is worthwhile to document this behavior.

That'd definitely be a good improvement on the upgrade experience so Windows users are aware of the behavior. I won't be able to get to it immediately but I'll write up an issue to address it
