### ISSUE TITLE
Why it doesn't install through go get anymore?

### ISSUE THREAD

**Issue by pillaiindu** [exercism/cli#516]
I tried Exercism an year ago, but now it doesn't install through `go get` anymore. I don't wanna download the binary.

**Comment by kytrinyx** [comment]
What command are you using? I'm able to install it with go get using:

```
go get github.com/exercism/cli/exercism
```

**Comment by NobbZ** [comment]
This will install the v3 version of the client, one should not use `go get` to install the client unless one wants to contribute!

Also remember, `go get` will only fetch sources and dependencies, to actually get a binary in `$GOPATH/bin` you need also to do a `go install github.com/exercism/cli/exercism` (IIRC).

Also remember to actually put `$GOPATH/bin` into your regular `$PATH`.

**Comment by NobbZ** [comment]
> I don't wanna download the binary.

Why not?

Prefered methods of the installations are as follows:

1. Installer or systems package manager,
2. user-local installation in user space from binary.

In general, assuming sufficient rights, method 1 should always be prefered over all other means because of the usual reasons (dependency management, uninstallation, etc).

If you want to install from source, while not contributing, I'd say the best way is to follow the contribution guide, but instead fetching the source from git, just download the source-tarball from the appropriate release and untar it at the correct place in the `$GOPATH`

**Comment by kytrinyx** [comment]
To compile from source:

* clone the repo
* follow the setup instructions in the contributing file
* `go build -o <PATH-TO-BINARY> exercism/main.go` where `<PATH-TO-BINARY>` is the full path to where you want the binary. For example, I typically put my binary in `~/bin`, which would make this `~/bin/exercism`

I'm going to go ahead and close this, since I believe it is resolved.
