### ISSUE TITLE
[nextercism] Add validation of auth token on configure step

### ISSUE THREAD

**Issue by NobbZ** [exercism/cli#537]
In #536 there was an empty error message printed at the user after he has configured an obviously malformed auth-token via `nextercism c -t` (it was taken from v1 instead of v2).

To make sure such things do not happen again, I think we should add validation of the auth token.

Validating if it is a valid UUID should be mandatory.

I do consider a verification request to the API as optional (a user might be offline when rolling back automated configuration tasks). Its not sure to me though if we should make the test request opt-in or opt-out though.

**Comment by kytrinyx** [comment]
Agreed. There's a whole mountain of improvements we need to make in terms of error messages.

**Comment by kytrinyx** [comment]
I think we should make the call to the API in order to validate the token.



> a user might be offline when rolling back automated configuration tasks

@NobbZ Would you elaborate on this one? I don't understand what this would entail. The `nextercism` CLI in its current form does not have any rollback. If you're using the CLI, then presumably you have access to the API in question (it might be the v2 API, or it might be something local on your machine if you're doing development work).

**Comment by NobbZ** [comment]
Some people (as me) might have an automated setup which builds computer setups from scratch.

We never know if those are connected to the internet during the setup phase.

Thats why I am proposing a "trust me" flag.

**Comment by kytrinyx** [comment]
Ah, yes! Thank you, that helps. In that case I would suggest making this a flag that is "off" by default.

**Comment by NobbZ** [comment]
Make the online check an opt out. If you make it opt in, noone will use it.

Katrina Owen <notifications@github.com> schrieb am Mo., 11. Juni 2018,
17:36:

**Comment by kytrinyx** [comment]
Sorry, yes, to clarify I want to have a specific flag to opt-out but by default we don't opt out.

**Comment by ccallergard** [comment]
I'm having a Go at this, and some of the other issues later probably.
It seems the `/ping` endpoint has no concern for tokens. Maybe it should, if token is provided?
Is there currently a way other than trying to download or submit something?

Also, I'm a bit unsure where to put this functionality. I suppose `troubleshoot` should validate the token too.
I think the `api` package makes sense?

**Comment by kytrinyx** [comment]
> I'm having a Go at this

Awesome, thank you!

> It seems the /ping endpoint has no concern for tokens. Maybe it should, if token is provided?

Yes, that could work. I was actually thinking a separate endpoint specifically for testing the auth, but having `/ping` take care of it might be better. Thinking about it a bit more, I think maybe I'd like a separate endpoint so that we can respond purely with a status code and not worry about parsing a response.

> Is there currently a way other than trying to download or submit something?

No, and I don't think doing that is great. Want to implement it against `/ping` for now, interpreting a `200 OK` as fine and `403 Unauthorized` as not fine? Then we can just swap out the endpoint later.

> Also, I'm a bit unsure where to put this functionality. [...] I think the api package makes sense?

Yeah, I think that's a good choice.

> I suppose troubleshoot should validate the token too.

Agreed, that would make sense.

Thank you for tackling this one!

**Comment by kytrinyx** [comment]
Alright, for now let's operate with the assumption that the endpoint will be the `GET /validate_token` endpoint on the API (so v2.exercism.io/api/v1/validate_token)
