### ISSUE TITLE
Set sensible defaults for workspace directory when configuring

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#541]
When someone configures their `nextercism` CLI for the first time, `workspace_dir` will be blank in the config.

We need to set a sensible default based on their operating system.

- Mac: `~/Exercism`
- Linux: `~/exercism`
- Windows: `%HOMEDRIVE%%HOMEPATH%\Exercism`

@rpottsoh do you have any suggestions for what a good default Exercism directory would be for Windows?

**Comment by rpottsoh** [comment]
I would think that c:\exercism would be ok.  The Installer also uses that as the, suggested, default location for the CLI as well.

Sent from my android device.

**Comment by kytrinyx** [comment]
Perfect, thank you!

**Comment by NobbZ** [comment]
I am not a windows user (as long as I have a choice), but `C:\exercism` is **not** OK.

Putting it anywhere outside of the user folder will cause trouble on corporate PCs or any system that houses more than one exercism student.

My choice where to stick to the same conventions as we do for Mac and Linux and put it under `%HOMEDRIVE%%HOMEPATH%\Exercism`.

**Comment by rpottsoh** [comment]
@kytrinyx I can't disagree with @NobbZ's recommendation, he's not wrong.  My reservation to going this route is that some students may find it more difficult to navigate to that folder while at the command prompt.  

Likely when `cmd` or `powershell` are executed the student will land at `%homedrive%%homepath%`.  This is fine, they will just need to realize that the only need to `cd exercism`.

I am concerned for those students whose initial prompt is something other than `%homedrive%%homepath%`.  Changing to their solutions folder becomes more cumbersome since it will be several levels deep and the student may not know where to look or how to get there.

I don't have a anyway to gauge how savvy your average Windows user is with the command prompt.  I would tend to lean more towards them being less comfortable than most users of other operating systems where working at the command prompt is a more commonly practiced.

I suggested `c:\exercism` as I suspect in most cases this will be OK and is much easier for students to locate via the command line or via Windows Explorer.

**Comment by rpottsoh** [comment]
Yes.  Realizing that the CLI can inform the student where it expects to find solutions.  :+1: :shipit:   I believe there is enough documentation to inform the student that they need to `cd` to the folder that contains their solution.  If there is a rash of Windows users that get stuck then we can deal with the nature of whatever the confusion might be at that time. 

In other words, at the moment, I can't think of how to make it any easier.

**Comment by kytrinyx** [comment]
> If there is a rash of Windows users that get stuck then we can deal with the nature of whatever the confusion might be at that time.

Agreed!

Ok, cool. Thanks both of you for helping hash this out ✨

**Comment by NobbZ** [comment]
> `cd $(exercism workspace)`

As far as I know, there is no equivalent to this construct in windows CMD, in PowerShell there might be, but I'm not knowledgable enough.

**Comment by kytrinyx** [comment]
> As far as I know, there is no equivalent to this construct in windows CMD

That's good to know. They can still use the workspace command to see where they need to change to, so I think it's probably fine. If it's not, we can see how to improve it.
