### ISSUE TITLE
Debug windows-specific problem in the submit relative path test

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#612]
There is a test in `cmd/submit_relative_path_windows_test.go` that is failing on Windows.
I've added a `t.Skip()` in order to keep the build green.

I don't know whether this is a problem in the test-setup, or whether this represents an actual problem for Windows-users using the CLI.

**Comment by nywilken** [comment]
So first pass this morning - the test passes after fixing the path separator `submittedFiles["\\file.txt"]` on line https://github.com/exercism/cli/blob/nextercism/cmd/submit_relative_path_windows_test.go#L58

Which based off the logic at https://github.com/exercism/cli/blob/nextercism/cmd/submit_relative_path_windows_test.go#L58

It would make sense  why that would be the case. 

Now, what I don't understand is why we need to include path separators when we submit the file. Is it so that at some point we can submit and store files in the same directory structure? For example, `(C:\\User\wilken\exercism\bogus-exercise\mysolution\file.txt)` should result in something like `\mysolution\file.txt`? 

If so, I would assume that the backend would know how to handle and store that so the respective user submission files are updated. If we only actually care about the filename and its content I would same lets drop everything but the filename. Especially, since at at the time we build the POST request we have the contents of the file.

Please let me know if I am missing something with how submit should work.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, @nywilken, as I think for now it makes sense to just stick with the leading path separator. If you feel strongly otherwise, then let's reopen and discuss it!
