### ISSUE TITLE
Windows 64-bit Exercism - Download exercise fails after upgrade

### ISSUE THREAD

**Issue by seesiva** [exercism/cli#662]
Attached is the issue screenshot. 
![image](https://user-images.githubusercontent.com/3206488/42986349-cec2dc0e-8c12-11e8-85b9-fc8509b3b6a7.png)

**Comment by NobbZ** [comment]
This is a known bug in the updater. It has been fixed in the current release (v3.0.5), but you need to update manually.

Please download the appropriate ZIP file for your system from https://github.com/exercism/cli/releases/latest and extract the contained `exercism.exe` to whereever your current exe is.

You can find the path of the old/broken executable using `where exercism`.

**Comment by seesiva** [comment]
Thanks. It did worked after the above said approach. You need to reconfigure with token to continue working with updated version.
