### ISSUE TITLE
Path issue when using Exercism CLI in Git Bash on Windows

### ISSUE THREAD

**Issue by sshine** [exercism/cli#734]
I gave feedback to someone today, but

    exercism download --uuid=...

gave me a directory with a file `\\src\\CollatzConjecture.hs` rather than a file `CollatzConjecture.hs` in the `src` directory. They said they were using Git Bash on Windows with the command

    exercism submit ./src/CollatzConjecture.hs

I suspect that the problem is either in `exercism submit` or in Git Bash giving it the file in some unexpected way.

I assume publishing submission UUIDs is not appropriate; let me know to whom I can send the UUID for further inspection. The submitter seems responsive and willing to debug the case.

**Comment by NobbZ** [comment]
This is a known issue. Probably the solution was submitted using a client prior to 3.0.9, which shall fix that bug.

**Comment by nywilken** [comment]
@sshine as @Nobbz said that was an issue we had with older clients. Please make sure you are running the latest cli as well `exercism version -l` which should download the files correctly. If the user resubmits the files it should fix things on the server side, but I don’t believe that is necessary since both the download and submit commands have been fixed.

**Comment by sshine** [comment]
Excellent, thank you. :)
