### ISSUE TITLE
Exercism v3.0.10-alpha.1 Testing

### ISSUE THREAD

**Issue by nywilken** [exercism/cli#742]
### What's this about? 

Before rolling out the next version of the Exercism command-line client we want to test that the latest changes for creating and storing exercise metadata (currently known as `.solution.json`) works as expected on all platforms, especially Windows.

The pre-release found [here](https://github.com/exercism/cli/releases/tag/v3.0.10-alpha.1) changes where exercise metadata is stored on a user's local filesystem.

```
C:\workspace-path\vimscript\hello-world\.exercism\metadata.json
```

Prior to this change the metadata file `.solution.json` was stored as a hidden file under the root directory for a given exercise.

```
C:\workspace-path\vimscript\hello-world\.solution.json
```

### How To Test?
1. Download the [v3.0.10-alpha.1](https://github.com/exercism/cli/releases/tag/v3.0.10-alpha.1) release.
1. Replace your existing `exercism` binary with the new release.
1. Choose one or more exercises within your workspace to test with.
1. Use the exercicm command-line client to submit and re-download the chosen exercises - see test cases below

#### Solution Migration Test Case
The command-line contains logic for migrating an existing `.solution.json` file to its new location `.exercism\metadata.json` upon submitting an exercise.

1. Verify that the exercise has an existing `.solution.json` file under its root directory (e.g <workspace-path>\ruby\hello-world\)
1. Change into the exercise directory and re-submit your solution `exercism submit hello-world.rb`
1. Verify that the submit command exits without error(s).
1. Verify that the file `.solution.json` has been removed.
1. Verify that a file called `metadata.json` was created under `<workspace-path>\track\exercise\.exercism\`

#### Download Existing Exercise Test Case
Downloading an existing exercise will not trigger a migration so the `.solution.json` file needs to be removed manually for now.

1. Verify that the exercise has an existing `.solution.json` file under its root directory (e.g `<workspace-path>\ruby\hello-world\`)
1. Change into the exercise directory and remove the file `.solution.json`
1. Re-download the exercise in question `exercism download --track ruby --exercise hello-world`
1. Verify that the download command exits without error(s).
1. Verify that a file called `metadata.json` was created under `<workspace-path>\track\exercise\.exercism\`

#### Download New Exercise Test Case
Downloading a new exericse should write the exercise metadata into the new `.exercism` directory.

1. Download the next exercise `exercism download --track ruby --exercise twofer`
1. Verify that the download command exits without error(s).
1. Verify that a file called `metadata.json` was created under `<workspace-path>\track\exercise\.exercism\`

### Post Test Clean-up
1. Remove the newly created .exercism directory for all of the exercises modified during your testing.
1. Re-install v3.0.9 of the exercism command-line https://github.com/exercism/cli/releases/latest
1. Restore the `.solution.json` metadata file by running the download command for each of the modified exercises.
1. Report any issues found while testing as comments on this issue.

**Comment by nywilken** [comment]
@kytrinyx @jdsutherland this issue documents that main test cases, I think.  Please advised if I missed anything. 

@FabienTregan @rpottsoh @Nobbz any chance you have some time to help tests on your end? It would be great to get your insight.

**Comment by NobbZ** [comment]
Not before sunday. I currently took a step back from everything, my grandmother died 2 weeks ago and saturday will be the funeral. Until after that exercism is only in passive mode.

**Comment by rpottsoh** [comment]
@nywilken I just finished running through all the scenarios you've proposed using the 64 bit Windows CLI.  The only thing I didn't notice happening was the deletion of the `.solution.json` file that I was expecting to be deleted during `Solution Migration Test Case`.  Otherwise everything worked fine.

At a command prompt Windows doesn't care about folder names that consist of only a dot name.  However Windows Explorer, doesn't play so nice.  You cannot even create a dot name only named folder (this can be done at a command prompt).  You cannot even rename a dot named only folder from Windows Explorer.  Deleting such a folder is not a problem.....  It may not be a big deal for most but might create confusion for some when forced to deal files/folders with dot only names in Windows.  I suggest a simple name like `data` or something to contain the file `metadata.json`.

**Comment by nywilken** [comment]
@Nobbz my deepest condolences to you and your family.

**Comment by nywilken** [comment]
@rpottsoh thanks for testing out the alpha release. Super helpful information. 

> The only thing I didn't notice happening was the deletion of the .solution.json file that I was expecting to be deleted during Solution Migration Test Case. Otherwise everything worked fine.

Hmmm, wondering if it has anything to do with it being a dot name file that the CLI is unable to delete it. You are running Windows 10, correct? I’ll try to repro on my end. Thanks for this. 

> I suggest a simple name like `data`

I think @kytrinyx mentioned this before, but it doesn’t have to be a dot name directory if it makes thing easier. @kytrinyx @jdsutherland thoughts?

**Comment by jdsutherland** [comment]
I don't know the details of AppVeyor but it's surprising that the tests pass (they assert that the legacy file is deleted). Maybe there is a Windows platform specific issue with `os.Rename`? I'd be very surprised if `os.Rename` didn't return an error if it was failing to remove the file. @rpottsoh can you check if the test suite passes?

**Comment by kytrinyx** [comment]
I wonder if there are specific "permission" bits on folders on Windows systems. I thought that Windows didn't care about the dot, and that it just made it a regular (not hidden) folder.

**Comment by FabienTregan** [comment]
There is no issue nor special behaviour I'm aware of on windows with respect to files/folders having name starting with a dot.
If you still need more test please tell me, I may find some time this evening (Paris hour, about 12 hours from now)

**Comment by nywilken** [comment]
> I think we should check the result of the test suite before further speculation.

Sorry for the confusion, my speculation was more of me thinking out loud with no actual reproduction attempt. I have not been able to reproduce this issue on Windows 8 as of this morning.  

My Execution Script 

1. Use v3.0.9 to download hello-world exercise
1. Verify .solution.json file is present (Cmd  and explorer)
1. Use v3.0.10-alpha.1 to submit `exercism submit hello-world.rb`
1. Confirm solution file has been deleted and that the metadata.json is present. 

I even set UAC to the highest level to see if that changes anything. It doesn’t!

@rpottsoh any chance you downloaded the exercise via v3.0.10 prior to submitting? If the file `.exercism\metadata.json` exists alongside the .solution.json the migration won’t actually happen because the cli only checks for the legacy file if it can’t find the new metadata file.

**Comment by jdsutherland** [comment]
> Sorry for the confusion, my speculation was more of me thinking out loud with no actual reproduction attempt. I have not been able to reproduce this issue on Windows 8 as of this morning.

Oh, I didn't intend to give the impression I was referring to you there. I was actually thinking of myself, as my initial post was overly speculative before I edited it.

**Comment by rpottsoh** [comment]
I don't have Go set up at the moment in order to run the tests.  I will re-run the check out steps again on my work Windows 7 (32 bit) system, and will report my findings.  This evening I will try to repeat the check out steps on my Windows 10 (64 bit) system and will pay closer attention to what happens with the JSON file, to see if it is deleted as expected when it is expected to be deleted.

**Comment by rpottsoh** [comment]
> I wonder if there are specific "permission" bits on folders on Windows systems. I thought that Windows didn't care about the dot, and that it just made it a regular (not hidden) folder.

Yes, it is possible to set permission levels, type of access granted to files and folders, and assign ownership; whether the contents of folders inherit from their parent folder etc.

The access/permission settings are not used much by the casual Windows user.

Having files/folder with names that start with a `.` is not illegal.  From my experience it is only the Windows Explorer that balks when you try to rename or create a file/folder that begins with a `.`.  Command prompt is no problem.  From within a custom app, shouldn't be a problem.  The fact the issue seems isolated to Windows Explorer should make the issue moot as far as it being some quirk of Windows.  Within my "Users" folder I see many files and folders that start with `.`.  A lot of these are created by Microsoft.  For me the annoyance is with Windows Explorer, why does it have to be the odd ball?  :smile: 

> any chance you downloaded the exercise via v3.0.10 prior to submitting? If the file .exercism\metadata.json exists alongside the .solution.json the migration won’t actually happen because the cli only checks for the legacy file if it can’t find the new metadata file.

Hmmm.  I can't be sure now that you bring this up.  I will be more careful during my Windows 7 evalulation.

**Comment by rpottsoh** [comment]
@nywilken I have repeated all of the check out steps on my 32 bit Windows 7 machine.  Everything worked fine and as expected.  Even the file `.solution.json` was removed when you expected it to be.  I will repeat the solution migration case in a little while on my Windows 10 system.

**Comment by rpottsoh** [comment]
@nywilken I repeated the solution migration case on my Windows 10 system.  Everything worked fine, the .solution.json file was removed as expected.

**Comment by nywilken** [comment]
Thanks for the testing. I will cut an actual 3.0.10 release tomorrow.

**Comment by nywilken** [comment]
v3.0.10 has been released.
