### ISSUE TITLE
submit: If I just submitted an identical iteration, tell me that

### ISSUE THREAD

**Issue by petertseng** [exercism/cli#768]
Let's say I've forgotten whether I've submitted my most recent changes or not. Maybe I stepped outside for a break, and forgot what I did right before stepping out. I'd like to know.

The API server currently tells this. If you changed something, it gives 201 Created and body `{}`. If you didn't change anything, it gives 400 Bad Request and body `{"error":{"type":"duplicate_iteration","message":"No files you submitted have changed since your last iteration"}}` . Making use of that information could help.

**Comment by kytrinyx** [comment]
I agree. We should display any `message` from the API on STDERR.

**Comment by Smarticles101** [comment]
I'm trying to become proficient at go so I think I'm gonna give this a stab. Would it be better to wait till #727 is merged?

**Comment by jdsutherland** [comment]
@Smarticles101 I implemented this before I noticed your comment. If you want to give it a shot, go ahead. I think we need not be concerned with #727 to make these changes. If you have any questions, I'd be happy to try to help.

One thing I'd point out is that I don't see a straightforward way to test this. It seems we'd want to mock a client so that we can setup a 400 API response but I don't see a way of injecting one without some heavier refactoring. I noticed that `cmd/download` has some behavior on `StatusCode` that isn't covered with tests so maybe we can live without test coverage on this.

**Comment by kytrinyx** [comment]
> I think we need not wait on #727 to make these changes.

Agreed! Wilken and I will deal with any conflicts/changes when we need to.



> It seems we'd want to mock a client so that we can return a 400 API response but we'd need a way of injecting it and that would require making additional changes.

Yeah, we should definitely be using `httptest` here. There's an example of how to do that in the download test; @jdsutherland might be right though that it could get tricky without some refactoring. If you can't get it to work in a reasonable time, then just skip it. Not sure what's "reasonable", basically: if it's too frustrating skip it and I'll take a look at adding tests later.

**Comment by jdsutherland** [comment]
Having looked again, I found this is actually straightforward to test. At first I imagined we had to mock the client but we can just set the response with using a new `httptest.Server`.
