### ISSUE TITLE
using exercism 

### ISSUE THREAD

**Issue by mayukudore** [exercism/cli#792]
I downloaded the boost and the CMake and also the visual studio. But the problem is how do I make use of it. I'm new to programming so  I will prefer if I get a step by step solution

**Comment by kytrinyx** [comment]
@mayukudore Exercism currently isn't a very good tool for folks who are completely new to programming. We're hoping to change that eventually, but until then my recommendation would be to join the CodeNewbie community. They're the most wonderful bunch of people on the internet, incredibly welcoming and supportive, and you're almost guaranteed to find others there who are at the same place in their learning journey as you are, and can help figure out next steps. Good luck ✨ 

I'm going to close this issue since it's not related to the CLI.
