### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ArchKoder** [exercism/cli#878]
![gradle](https://user-images.githubusercontent.com/40110953/63879955-607f5a80-c9ea-11e9-9abb-e95023f6628b.PNG)

**Comment by NobbZ** [comment]
Hi @ArchKoder!

The exception is as expected, as the provided stub file is compilable and runnable but does not pass the tests. You need to implement the function to properly return the expected value.

Also this repository is solely for the `exercism` command line tool, not for track specific build tools or their exercises.

Please file further tickets at github.com/exercism/exercism. If they are inappropriate in that repository they will be moved into a repository that suites the issue.

Last but not least, please provide some words that explain the problem you encounter as well as copy and paste the error you see rather than providing a screenshot. There is no broadband in most places of earth. And even if its available data might be expensive.

**Comment by ekingery** [comment]
This seems resolved / close-able. Please re-open if I am mistaken!
