### ISSUE TITLE
Can't submit on Windows

### ISSUE THREAD

**Issue by markl11** [exercism/cli#919]
I can't submit an exercise on windows - any idea what I am doing wrong? 

thanks very much in advance!

c:\Exercism\exercises>exercism workspace
C:\Users\markl\Exercism

c:\Exercism\exercises>dir
 Volume in drive C is Windows
 Volume Serial Number is 8C88-E14B

 Directory of c:\Exercism\exercises

21/02/2020  18:42    <DIR>          .
21/02/2020  18:42    <DIR>          ..
21/02/2020  18:42                22 helloworld.sh
               1 File(s)             22 bytes
               2 Dir(s)  1,208,304,508,928 bytes free

c:\Exercism\exercises>exercism submit helloworld.sh
Error: CreateFile C:\Users\markl\Exercism: The system cannot find the file specified.

c:\Exercism\exercises>

**Comment by NobbZ** [comment]
You need to download the exercise first, using the command that is provided on the exercises page. 

For `hello-world` on the `bash` track (it looks like you want to follow that track because of the filename `helloworld.sh`) the command is `exercism download --exercise=hello-world --track=bash`.

This command will download the exercise files into `C:\Users\markl\Exercism\bash\hello-world`, and you should solve and submit it from there.

Please be aware of the fact that doing the `bash` track on windows requires you to install either a POSIX compatibility layer like cygwin or MSYS2, or activate WSL.

Though doing exercism in WSL requires you to treat the WSL like a linux installation of exercism.

**Comment by markl11** [comment]
that worked - thankyou for your help.
