### ISSUE TITLE
Can't resubmit two-fer exercise - CLI is up to date - Error says file not found

### ISSUE THREAD

**Issue by lacyboisvert** [exercism/cli#959]
<img width="618" alt="Screen Shot 2020-09-04 at 7 33 13 PM" src="https://user-images.githubusercontent.com/70784871/92294036-8c7ac900-eee5-11ea-8172-afcf0aec0598.png">
<img width="1043" alt="Screen Shot 2020-09-04 at 7 33 26 PM" src="https://user-images.githubusercontent.com/70784871/92294042-96043100-eee5-11ea-9422-20cc23754557.png">

I cannot resubmit my two-fer dart exercise. Error says file not found.

**Comment by kotp** [comment]
The capital letter "E" in Exercism is suspect to me.  While the case may not matter for the file system or operating system in regards to directory name, it does matter for the CLI.

The expected directory is `/Users/lacyboisvert/exercism/dart/two-fer` while the exercise being submitted would be `two_fer.dart` while in the above folder.

The prompt might look like this for you:

```sh
lacyboisvert@Lacys-MBP two-fer % exercism submit lib/two_fer.dart
```

The complete, fully written out path would not be necessary, as it is expected that you would submit from the exercise folder.

Again, I believe the problem is partly the capitalized folder name of `Exercism`.  But also, the exercise file being submitted is unexpected.  Compare to the hello-world exercise to see what worked for you for that first exercise.

**Comment by lacyboisvert** [comment]
The exercism submit lib/two_fer.dart  was the one that worked. Thank you for your help!
