### ISSUE TITLE
Allow submitting solution without specifying files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cli#991]
One of the most requested features for the CLI is to be able to submit a solution without having to explicitly specify the files to submit. With Exercism v3, each exercise will have a `.meta/config.json` file (see https://github.com/exercism/docs/blob/main/building/tracks/concept-exercises.md#file-metaconfigjson and https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson). This file contains a `files` property with a nested a `solution` string array property. The values in the `solution` array are the names of the files that the student should work on. In other words: these file names can be used to determine the files that should be submitted, provided no files were specified by the student.

As an example, consider the following `.meta/config.json` file:

```json
{
  "files": {
    "solution": ["Lasagna.fs"],
    "test": ["LasagnaTests.fs"],
    "exemplar": [".meta/Exemplar.fs"]
  }
}
```

If the student runs `exercism submit` (no file names specified), the CLI should then interpret this as if the student ran `exercism submit Lasagna.fs`.

Note that if a student _does_ specify files, the CLI should use those and ignore the `.meta/config.json` file.

Also note that the `solution` property is an array, so it can contain multiple files (which should all be submitted).

**Comment by andrerfcsantos** [comment]
I'd like to work on this!

**Comment by andrerfcsantos** [comment]
I took a look at the code and I think I have a good idea where to make the changes. I have one question though.

About the `.meta/config.json` file - since it is in the metadata folder and "not presented to the user" I assume this means that it will not be shipped when the student downloads the exercise and we must grab this file from the repository. Am I correct in this assumption? If so, should we fetch the file when the students tries to submit the solution and put it somewhere for future use like the `.exercism` folder in each exercise, or should we fetch `.meta/config.json`  every time the student tries to submit?

**Comment by ErikSchierboom** [comment]
Good question. We definitely want the file to be present locally. Maybe the `.exercism` folder would be a good location for that. @iHiD any thoughts?

**Comment by iHiD** [comment]
It should definitely be downloaded with the exercise IMO. The issue, of course, is that for many historic solutions it won't be there. So I'd say download it and store it in `.exercism`, and if at submit time it is missing, download it then too.

**Comment by Rustery** [comment]
I think there should be a link to #975 issue with the same question.

**Comment by andrerfcsantos** [comment]
> It should definitely be downloaded with the exercise IMO. The issue, of course, is that for many historic solutions it won't be there. So I'd say download it and store it in `.exercism`, and if at submit time it is missing, download it then too.

Sounds good, will implement like this.

One additional question:  currently I'm grabbing the exercise config file from the track repo, but looking at the code it seems we are getting most of the info (including other config files) from the API. Is getting the file directly from the repo the intended way to do this. Is there (or will be) an API endpoint for this file?

Related to the previous question: if we do get the file from the repository, the link to the  `.meta` file depends on if the exercise is a concept exercise or concept (e.g https://github.com/exercism/go/blob/main/exercises/practice/accumulate/.meta/config.json, note the `/practice/` part of the link), which means that we also must know the kind of exercise, which I guess we can know from the `config.json` in the track repos (e.g [https://github.com/exercism/go/blob/main/config.json](https://github.com/exercism/go/blob/main/config.json)). Should we also grab this file? Can we know this via the API?

**Comment by iHiD** [comment]
The API should have this file added to its list of sent files. I think it already does for v3 (@ErikSchierboom?) We don't use GitHub as a production source for anything.

**Comment by ErikSchierboom** [comment]
@andrerfcsantos @iHiD and I have discussed this, and this is what we decided upon:

1. The API will return the `.meta/config.json` file along with the exercise files
2. The CLI should downloaded any files in the `.meta` directory to the `.exercism` directory

This means that when an exercise is downloaded, there should be a `.exercism/config.json` file on the student's file system, _not_ an `.meta/config.json` file. Makes sense?

**Comment by ErikSchierboom** [comment]
@andrerfcsantos Small bump regarding the above question: could you indicate what the status of this issue is?

**Comment by andrerfcsantos** [comment]
Hi @ErikSchierboom

It has been a couple of busy weeks and I hadn't the chance to look further into this issue.

Starting next week I'll have more free time and I plan to look into this issue.

**Comment by andrerfcsantos** [comment]
@ErikSchierboom I'm happy to hand over this issue to @jodihamann

**Comment by asarkar** [comment]
+1. Cherrypicking individual files is prone to mistake. I should be able to do `exercism submit <exercise_dir>` from anywhere, since the CLI already knows the workspace path, or `exercism submit`, in which case, the CLI should consider the current directory as an exercise.

**Comment by andrerfcsantos** [comment]
I'll try to take a look at this again, now that I'm more familiar with the codebase.

I noticed there's already a PR created before this issue that attempts to address this: https://github.com/exercism/cli/pull/929

The algorithm used there is different than the one discussed here and is before v3. Should I create a new PR if I get to look at this?

> Support git-style globs. This enables proper handling even if a student breaks out a part of their work into a separate file.

This can be done easily.

> Support a fallback to a key in the track-level config.json if files.solution does not exist in the per-exercise config.json. For Rust, and likely for other languages, the set of default files to submit doesn't actually change per exercise. Of the two, this is the more desirable feature.

My question here is how exactly we would get the track-level config. It'd be probably best if this config is provided by the API, but I'm not sure there's an endpoint for this. Grabbing the file directly from github doesn't seem a good idea, since the link contains the repo name and a branch name, both of which can change.

**Comment by coriolinus** [comment]
We probably don't need the track-level configuration files anymore now that
every exercise can have a `files` key within its `.meta/config.json`. I
don't think that used to be the case, but now, the CLI could just work like
this:

1. User specified no files, so we're in autosubmit mode
2. Look for the `.meta/config.json` and load `files.solution`. If not
present, bail.
3. Resolve globs.
4. Submit all matching files.

**Comment by ErikSchierboom** [comment]
> but I thought you were suggesting checking the track-level config as an additional fallback for not having .meta/config.json with a files.solution.

We don't support `files.solution` to be empty (which is verified by `configlet`), so that fallback is not needed/supported.

**Comment by ErikSchierboom** [comment]
> Feel free to take a look. Didn't include the "glob" feature because I think we need to discuss it a bit more and it's probably best if this feature is as self-contained as possible.

Good call. I don't think we need this at the moment. Maybe for some time in the future, but then we'd also have to update the website to handle it.

**Comment by coriolinus** [comment]
Follow-up issue for globs subfeature: https://github.com/exercism/exercism/issues/6399

**Comment by coriolinus** [comment]
I mean, that would be great, but it's a relatively high-complexity feature.
Bare minimum, the CLI would need to know where the track repo is, so that
it can fetch the track-level `config.json`, and then there's the question
of when do you invalidate the cache, etc. Now that exercise-level
config.json files are ubiquitous, I'd prefer progress on the feature over a
slow design process for handling track-level config.json fallbacks.
